AMReX-Codes/IAMR

- Exec/run2d/inputs.2d.lid_driven_cavity
- Exec/run2d/inputs.2d.poiseuille
- Exec/run3d/inputs.3d.lid_driven_cavity
- Exec/run3d/inputs.3d.poiseuille
- Source/GODUNOV_F.H
- Source/Godunov.H
- Source/Godunov.cpp
- Source/NavierStokesBase.H
- Source/NavierStokesBase.cpp
- Source/Src_2d/GODUNOV_2D.F
- Source/Src_3d/GODUNOV_3D.F
- Source/main.cpp
Added functionality for checking whether steady-state has been reached, and if so, stopping the simulation. This is particularly useful for problems where a steady system is sought, but where one doesn't know beforehand how long time we will require to reach such a state. 
The user activates steady-state checking by setting the input parameter "ns.stop_when_steady" to true (or 1). Additionally, one should set the parameter "ns.steady_tol", which is the accompanying tolerance. If the velocity magnitude changes by less than steady_tol from one iteration to the next, the system is deemed to have reached steady-state. 
Both lid-driven cavity and Poiseuille examples (2D+3D) successfully reach steady-state and consequently stop the simulation.
> Stop when steady

- Source/Diffusion.cpp
The RHS is already multiplied by dt in PeleLM mac_sync and diffuse_sync
is only used in PeleLM.
> Remove scaling by dt in constructing RHS of sync diffusion solve.

- Source/NavierStokesBase.cpp
It should fix the restart problem with PeleLM FlameSheet_restart RegTest.
> Add forgotten init of transport coefficient NSB container when restarting.

- Source/Diffusion.H
- Source/Diffusion.cpp
- Source/NavierStokes.cpp
- Source/NavierStokesBase.H
- Source/NavierStokesBase.cpp
1. Cell-centroid viscosity is now passed diffuse_tensor_velocity() for use in EB solve
2. Ensures bCoeffs are considered on centroids for EB
> Cgilet cc visc

- Source/NS_getForce.cpp
- Source/NavierStokes.cpp
- Source/NavierStokesBase.cpp
Recent changes in NSB::getForce were causing non-EB compilations to crash.
This commit fixes the crash, but regression tests for both EB and non-EB problems with non-zero gravity have O(1) differences.
> Fix crash for non-EB.

- Source/NavierStokesBase.cpp
Turn off tiling in offending loop for now. Recent GPU updates
removed a temporary fab still needed in IAMR (but not PLM),
introducing a tiling bug. Once IAMR's getForce is updated,
tiling will be turned back on.
Along with the SyncInterp() fix, this fixes most of the regression tests.  The HotSpot, TaylorGreen and Part-2d tests still show large diffs.
> Temporary fix for tiling bug in NSB::estTimeStep().

- Source/NavierStokesBase.cpp
Don't need all the boundary filling junk that was at the bottom of this function.
> Remove a bunch of filling stuff at the bottom of create_umac_grown

- Source/MOL/iamr_mol.cpp
In the redistribution algorithm, the computation of the non-conservative term should include the cell itself. This will change the regression tests with EB.
> Including the cell itself in the non-conservative computation

- Source/MOL/iamr_mol.cpp
I will revert the changes from this PR. We have decided to go with the version of **not** including the cell itself in the non-conservative computation.
> Revert "Including the cell itself in the non-conservative computation"

- Exec/run2d/inputs.2d.average_hotpost
- Exec/square_grid_turbulence/inputs.3d.square_grid
- Source/Make.package
- Source/NS_BC.H
- Source/NS_average.cpp
- Source/NS_derive.H
- Source/NS_derive.cpp
- Source/NS_setup.cpp
- Source/NavierStokes.cpp
- Source/NavierStokesBase.H
- Source/NavierStokesBase.cpp
Just put ns.avg_interval = something (>0) to activate the feature.
avg_interval controls the interval of time-steps when a solution is integrated to the average.
The average is dumped in each plotfile.
Do not forget to add "velocity_average" in amr.derive_plot_vars.
> [Feature] On-the-fly time-averaging of velocities

- Source/Godunov/iamr_godunov.cpp
The array type can be lambda captured to device by recent versions of CUDA.
However, it does not work with HIP and DPC++.  So we switch to GpuArray
instead.
> Use GpuArray instead of C array

- Source/NavierStokesBase.cpp
> Fix NSB header for (EB)MOL & (EB)Godunov, always need the non-EB

- Source/EBUserDefined.H
- Source/Make.package
- Source/NS_init_eb2.cpp
Add a hook to NS_init_EB to enable the definition of a user-defined geometry.
The file EBUserDefined.H contains a dummy version that'll be overwritten by copying this file in your local folder.
> Feature hook EB geometry

- Source/Diffusion.cpp
- Source/FluxBoxes.H
- Source/MacProj.cpp
- Source/NS_LES.cpp
- Source/NS_average.cpp
- Source/NS_derive.cpp
- Source/NS_getForce.cpp
- Source/NS_util.cpp
- Source/NavierStokesBase.H
- Source/NavierStokesBase.cpp
- Source/Projection.cpp
- Source/SyncRegister.cpp
Remove most of the compiler warnings pertaining to unused variables, shadowed variables or pedantic extra ;
I didn't remove but simply commented out some function unused arguments because I was unsure of their previous usage.
> Reduce compiler warnings

- Source/NavierStokesBase.cpp
When the `CellConstProt_T` interpolater enum is in use for `NavierStokesBase::SyncInterp(which_interp)`, the code segfaults with an out-of-bounds error due to accesses on `coarsedata` using the same grid as `finedata`. This PR tries to fix that. Tested on CPU (local) using the "bubble" inputfile in Exec/run2d.
> Fix OOB access on coarsedata in NavierStokesBase::SyncInterp()

- Util/pprocConvOrder.py
Changed print statement in `elif( pproc_type == "diffsamedomain" )`
> Fixed typo in print statement in Util/pprocConvOrder.py

- Source/Diffusion.H
- Source/Diffusion.cpp
- Source/NavierStokes.H
- Source/NavierStokes.cpp
- Source/NavierStokesBase.H
- Source/NavierStokesBase.cpp
Remove Diffusion::visc_coef because it's not used in Diffusion.
Move checks on visc_coef from Diffusion to NavierStokes (which actually uses visc_coef).
Remove NavierStokesBase::Initialize_specific. 
Minor clean up of NavierStokes Initialize for clarity and to quiet compiler warnings.
> Remove Diffusion::visc_coef array and clean up of NavierStokes initialization.

- Source/NavierStokesBase.cpp
Make new `NSB::create_umac_grown` that uses `FillPatchTwoLevels`. 
This fixes an error wherein the valid fine face values at the coarse-fine interface were not being used in the computation of fine ghost cell values. Previously, IAMR used `HydroUtils::create_constrained_umac_grown` which relies on `InterpFromCoarseLevel` which uses interpolated coarse values at the coarse-fine interface rather than the valid fine data that exists there in this case. Differences are likely subtle, as `create_constrained_umac_grown` makes further corrections after the interpolation.
> Update create umac grown

- Source/MacProj.cpp
- Source/NavierStokes.cpp
During the MAC sync, we need to reconstruct the edge states exactly
as we made them during the advection step of advance. This was not
happening correctly for the scalars when using Godunov with divU!=0
or, for divU=0, non-conservative scalars with external forcing.
This does not affect the mac_sync_compute version where edge states
are passed in and not recomputed.
> Fix mac sync

- Tutorials/TaylorGreen/benchmarks/ViscBench.cpp
Updated the ViscBench.cpp file for the Taylor-Green benchmark. The L1, L2 and L_{inf} norms should now be calculated correctly, using the built-in MultiFab `norm0`, `norm1` and `norm2` member functions.
> Added fixed norm calculations for ViscBench.cpp
